# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: santosh
      MONGO_INITDB_ROOT_PASSWORD: santosh

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: santosh
      ME_CONFIG_MONGODB_ADMINPASSWORD: santosh
      ME_CONFIG_MONGODB_URL: mongodb://santosh:santosh@mongo:27017/
      ME_CONFIG_BASICAUTH: false
